# Site settings
title: Simeosoft
twitter_username: simeosoft_tw
name: Carlo Simeone

# Build settings
markdown: kramdown

intro:
    Attività di consulenza software relativa alla progettazione, pianificazione, deployment e manutenzione di applicativi in ambito web e desktop.
    
#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/simeosoft
 - title: LinkedIn
   url: http://it.linkedin.com/in/carlosimeone

#Any buzzword skills you want to include
skills:
 - Linux
 - Gradle
 - Java
 - SQL
 - REST
 - Tech Architecture

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: http://automateddeveloper.blogspot.com/feeds/posts/default

#Work experience is required
roles:
 - title: Senior Engineer
   start: 2009
   end: Ongoing
   employer: Simeosoft di Carlo Simeone
   description: Consulenza software.
 - title: Responsabile sistemi/infrastruttura di rete/Analista
   start: 2003
   end: 2008
   employer: Itelcom
   description: Responsabile della infrastruttura di telecomunicazione e del sistema informativo
 - title: Responsabile software (socio operativo/membro CdA)
   start: 1999
   end: 2002
   employer: INDI Spa
   description: Realizzazione sistemi informatici client/server e web based, internet security
 - title: Socio Amministratore
   start: 1997
   end: 1999
   employer: Digital Age
   description: Realizzazione sistemi informatici e reti locali
 - title: Systems & Network Administrator
   start: 1995
   end: 1997
   employer: CM Telecommunications
   description: Responsabile della infrastruttura di telecomunicazione, del sistema informativo e del gruppo S&N
 - title: Analista Programmatore/Sistemista
   start: 1988
   end: 1995
   employer: Etnoteam Adriatica Spa
   description: Analista/Programmatore
 - title: Sviluppatore software
   start: 1984
   end: 1987
   employer: SIPE Snc
   description: Analista/Programmatore
   

#Education is required
education:
 - level: Perito Industriale spec. Elettronica
   date: 1980
   subject: 
   school: ITIS Vito Volterra Ancona

#This section is optional (as is the image link below)
#coursera:
#   profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
#   courses:
#    - title: Functional Programming Principles in Scala
#      link: https://www.coursera.org/course/progfun
#      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
#      date: September 16, 2013
#    - title: Algorithms Design and Analysis, Part 1
#      link: https://www.coursera.org/course/progfun
#      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
#      date: April 28, 2014

#List of interesting Github repo/projects to include - optional
#github:
# - robhinds/learning-neural-networks
# - robhinds/akka-http-rest-api-sample

#Stackoverflow flair is optional
#stackoverflow:
#   profileurl: http://stackoverflow.com/users/258813/rhinds
#   flairimageurl: http://stackoverflow.com/users/flair/258813.png

#Mobile apps section is optional
apps:
 - name: KJItalia
   platform: Android
   url: .
   description: App test gestione automobile (Jeep Cherokee) 

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Linux</strong>: Esperienza sistemistica, di rete e programmazione su diversi sistemi e dialetti Unix/Linux. <br/><br/>
   <strong>Web Development</strong>: Sviluppo di applicazioni complesse in PHP, Java e altri linguaggi. Realizzazione siti di commercio elettronico.<br/><br/>
   <strong>Analisi e programmazione</strong>: Esperienza pluriennale su molteplici architetture e linguaggi adottando metodologie di sviluppo avanzate.<br/><br/>
